import 'dart:io';
import 'package:csv/csv.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../../groups/models/group_model.dart';
import '../../expenses/models/expense_model.dart';

class ExportService {
  // ── PDF Export ──────────────────────────────────────────────────────────
  static Future<void> exportToPdf({
    required GroupModel group,
    required List<ExpenseModel> expenses,
  }) async {
    final doc = pw.Document();
    final total = expenses.fold<double>(0, (sum, e) => sum + e.amount);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          // ── Header ──────────────────────────────────────────────
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: const pw.BoxDecoration(color: PdfColor.fromInt(0xFF134E4A)),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Splitly',
                    style: pw.TextStyle(
                        color: PdfColors.white,
                        fontSize: 22,
                        fontWeight: pw.FontWeight.bold)),
                pw.Text(group.name,
                    style: const pw.TextStyle(color: PdfColors.white, fontSize: 14)),
              ],
            ),
          ),
          pw.SizedBox(height: 16),

          // ── Summary ─────────────────────────────────────────────
          pw.Text('Expense Summary',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text('Total expenses: ${expenses.length}'),
          pw.Text('Total amount: ${group.currency} ${total.toStringAsFixed(0)}'),
          pw.SizedBox(height: 16),

          // ── Table ───────────────────────────────────────────────
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            columnWidths: const {
              0: pw.FlexColumnWidth(3),
              1: pw.FlexColumnWidth(2),
              2: pw.FlexColumnWidth(2),
              3: pw.FlexColumnWidth(2),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColor.fromInt(0xFFCCFBF1)),
                children: [
                  _cell('Title', bold: true),
                  _cell('Category', bold: true),
                  _cell('Paid By', bold: true),
                  _cell('Amount', bold: true),
                ],
              ),
              ...expenses.map((e) => pw.TableRow(
                children: [
                  _cell(e.title),
                  _cell(e.category),
                  _cell(e.paidByName),
                  _cell('${e.currency} ${e.amount.toStringAsFixed(0)}'),
                ],
              )),
            ],
          ),

          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by Splitly — Your Circle. Your Hisaab.',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final bytes = await doc.save();
    await Printing.sharePdf(bytes: bytes, filename: '${group.name}_summary.pdf');
  }

  static pw.Widget _cell(String text, {bool bold = false}) => pw.Padding(
    padding: const pw.EdgeInsets.all(6),
    child: pw.Text(
      text,
      style: pw.TextStyle(
        fontSize: 10,
        fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
      ),
    ),
  );

  // ── CSV Export ──────────────────────────────────────────────────────────
  static Future<void> exportToCsv({
    required GroupModel group,
    required List<ExpenseModel> expenses,
  }) async {
    final rows = <List<dynamic>>[
      ['Title', 'Category', 'Paid By', 'Amount', 'Currency', 'Date'],
      ...expenses.map((e) => [
        e.title,
        e.category,
        e.paidByName,
        e.amount.toStringAsFixed(2),
        e.currency,
        e.createdAt.toIso8601String(),
      ]),
    ];

    final csvData = const ListToCsvConverter().convert(rows);
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/${group.name}_expenses.csv');
    await file.writeAsString(csvData);

    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'Splitly expense export for ${group.name}',
    );
  }
}